### ISSUE TITLE
Support for 3.0.0-preview5-19227-01

### ISSUE THREAD

**Issue by nj-db** [jsakamoto/Toolbelt.Blazor.HotKeys#1]
Hi,
Will Toolbelt.Blazor.HotKeys be supporting 3.0.0-preview5-19227-01 any time soon.
Nick

**Comment by jsakamoto** [comment]
Thank you for your comment.

I think, Toolbelt.Blazor.HotKeys ver.4.0.0 package would be works fine on 3.0.0-preview5-19227-01.

See also: commit a2cc66a91b1a7fcf7c68447b098b58eda6027c0f

If you are running into some problems, please tell me about it.

**Comment by nj-db** [comment]
Thanks for your prompt reply.

It was a strange bug in the NuGet UI Updates feature. I would update all of the packages to the latest prerelease versions, build the project and the packages would rollback to their previous versions.

Editing the PackageReferences directly in the csproj file like in you referenced commit resolved the issue.
