### ISSUE TITLE
Autocomplete throws TypeError

### ISSUE THREAD

**Issue by jeffraska** [jsakamoto/Toolbelt.Blazor.HotKeys#10]
Version: 10.0.0
When autocomplete in input is used, the parameter `keyName` in `convertToKeyNameLevel2` method is undefined which results in exception.

![2021-02-12_08-52-53](https://user-images.githubusercontent.com/5276204/107742786-fd81a080-6d0f-11eb-96db-87e296e17573.gif)

**Comment by jsakamoto** [comment]
Thank you for reporting!

I fixed this problem just now.

Please try out the latest version.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys/10.0.1

Thanks!

**Comment by jeffraska** [comment]
Works great, thank you very much fast.
