### ISSUE TITLE
Feature Request: Add support for Media Key "Stop"

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [jsakamoto/Toolbelt.Blazor.HotKeys#21]
Hello,

you support media keys but I'm missing support for media key "stop". Is there any possibility?

Thanks :)

**Comment by jsakamoto** [comment]
@NeoCoderMatrix86 Thank you for the feedback!

Today, I released the new version of the "Blazor HotKeys" NuGet package.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys/12.1.0

I improved that version that supported the `MediaStop` key and numerous `LaunchApplication*` keys.

Please try it out. :)

**Comment by NeoCoderMatrix86** [comment]
Works perfect, thanks :)!
