### ISSUE TITLE
Problem with not disposing services as soon as "HotKeys.CreateContext()" called

### ISSUE THREAD

**Issue by marcelgoldstein** [jsakamoto/Toolbelt.Blazor.HotKeys#22]
**Context:**
Blazor Server App from default template on .net 6.0.
Normally, when the session ends (by closing the tab) the ServiceProvider gets disposed and all instantiated service get disposed as well when they implement `IDisposable `or `IAsyncDisposable`.

**Problem:**
I am having problem with the disposal of registered services when using hotkeys. As soon as I call `HotKeys.CreateContext()` the dispose methods of my services registered as "scoped" are not invoked anymore. 

To illustrate the behavior I have attached a sample project [BlazorApp14.zip](https://github.com/jsakamoto/Toolbelt.Blazor.HotKeys/files/8442483/BlazorApp14.zip) that registers a "CounterService" as "scoped". In the constructor the instances add to a static list and on dispose remove from this list. The count of this list gets displayed in the counter-component. Each counter-component invokes `StateHasChanged` in an endless loop to see the current state without the need to interact manually.

Working example:
Now I open up the counter-component in multiple browser tabs => the count increases. 
When closing a browser tab => the count decreases.
![working](https://user-images.githubusercontent.com/32980128/162192062-e2f6c7a0-332a-4165-b227-790faab5fd4c.gif)

Not working example:
Comment in the `HotKeys.CreateContext()` inside the counter-component.
Now when opening multiple tabs => the count increases.
When closing a browser tab => **no dispose and therefor no remove from the list happening - the count stays.**
![not_working](https://user-images.githubusercontent.com/32980128/162192073-27ff79d0-cb97-4ab1-8816-911cd13bd0a4.gif)

**Comment by jsakamoto** [comment]
@marcelgoldstein Thank you for reporting!

I was able to figure out the root reason for this problem due to your kindness report, and I fixed it!

I published the new version just now.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys/12.1.1

Could you try it out?

**Comment by marcelgoldstein** [comment]
I have tested with the new version 12.1.1 and it seems to work fine. 👍

Thanks for fixing this problem so incredibly fast, much appreciate.

**Comment by jsakamoto** [comment]
@marcelgoldstein 

> Thanks for fixing this problem so incredibly fast, much appreciate.

You are welcome! 
Your issue report is really excellent. 
Especially what you attached the zipped project file that would reproduce the problem is a massive contribution to reducing the duration of fixing the problem.

Again, thank you for your cooperation!
