### ISSUE TITLE
Other keyboard layouts

### ISSUE THREAD

**Issue by xtomik** [jsakamoto/Toolbelt.Blazor.HotKeys#25]
I would like to make keyboard shortcut to `?` to show a cheat sheet.
But I need to support several keyboard layouts.

On US keyboard it's `SHIFT + /`

On CZ keyboard it's `SHIFT + ,`

Czech keyboard layout: https://docs.microsoft.com/cs-cz/globalization/keyboards/kbdcz1.html

Is it possible to add `expectedNativeKey` parameter to `HotKeysContext.Add(..)`

so the HotKeyEntry is triggered only when the `expectedNativeKey` matches nativeKey ?
```
.Add(ModKeys.Shift, Keys.Slash, ShowCheatSheet, "Show cheat sheet.", expectedNativeKey: "?")    // for US keyboard
.Add(ModKeys.Shift, Keys.Comma, ShowCheatSheet, "Show cheat sheet.", expectedNativeKey: "?")   // for CZ keyboard
```

**Comment by jsakamoto** [comment]
@xtomik Thank you for your proposal!

Please let me consider well how to resolve this problem this weekend.

**Comment by jsakamoto** [comment]
@xtomik 
Today, I published the new version v.13.0.0 of this library as a preview edition.

https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys/13.0.0-preview.1#versions-body-tab

This new version expose the `AddByKey()` method for the `HotKeyContext` class. The `AddByKey()` method allows you to add hot keys based on a DOM event's native key name, like this.

```cs
... HotKeys.CreateContext()
  .AddByKey(ModKeys.None, "?", ShowCheatSheet, "Show cheat sheet.")
  ...
```

Would you try to use that preview version?

**Comment by xtomik** [comment]
@jsakamoto Thanks, I'll test it.

**Comment by xtomik** [comment]
@jsakamoto I've tested it and it works fine.

Thank you.
