### ISSUE TITLE
Default browsers shortcuts

### ISSUE THREAD

**Issue by lukas9812** [jsakamoto/Toolbelt.Blazor.HotKeys#27]
Hello,
if I want to trigger custom hot key action (CTRL + S) it always triggers a default Chrome shortcut for saving whole html page locally.
Do you have please some hints how to enable my hot key ? 
![image](https://user-images.githubusercontent.com/75972605/226600416-8f717a3e-4f8d-4cb4-bdf3-e02f4e8d9e2f.png)

Many thanks!

**Comment by jsakamoto** [comment]
@lukas9812 You can do that with [Blazor HotKeys**2**](https://github.com/jsakamoto/Toolbelt.Blazor.HotKeys2) and its `ModCode` and `Code` parameters, not Blazor HotKeys. Blazor HotKeys is already deprecated. I attached the sample code to this post. Please take a look at it.

- [📦BlazorWasmApp1.zip](https://github.com/jsakamoto/Toolbelt.Blazor.HotKeys/files/11045342/BlazorWasmApp1.zip)
