### ISSUE TITLE
Can you support only ctrlKey or MetaKey pressed?

### ISSUE THREAD

**Issue by Yavari** [jsakamoto/Toolbelt.Blazor.HotKeys#4]
I need to replicate $event.ctrlKey and $event.metaKey from a onclick event and was hopping that your library would support to bind modKeys without any other keys pressed. Is this possible?

**Comment by jsakamoto** [comment]
I did not know there are those needs to catch meta key only keypress events.

Anyway, this is an interesting suggestion for me.

I'll try to implement the feature of this issue.

**Comment by jsakamoto** [comment]
I published Blazor Hotkeys v.8.1.0 which supports meta keys events.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys/8.1.0

You can see the sample code on how to capture Ctrl key press events.

- https://github.com/jsakamoto/Toolbelt.Blazor.HotKeys/blob/master/SampleSites/Components/Shared/MainLayout.razor#L49

There is nothing special. You can capture meta keys just specify those meta key's `Keys` enum values.

**Comment by Yavari** [comment]
Thank you! I will try it out this weekend

**Comment by Yavari** [comment]
Thank @jsakamoto, I tried it out today and it works the way you have implemented it and I think it will be very useful. It will however not work for the scenario I was looking for. I wanted to to use it in combination with a mouse click. 

I want to do an action if the user holds Ctrl and left clicks the mouse button. That will only work if the library either also supports mouse events which seems to be out of scope or if the library can support Key Up events.

**Comment by jsakamoto** [comment]
@Yavari 

> I wanted to to use it in combination with a mouse click.

If you want to just do it, you will not require this library.
Instead, you can do it plain Blazor built-in features, like this:

```razor

<p @onclick="OnClickTitle">
    <b>Click here</b>
</p>

<p>
    <button type="button" @onclick="OnClickButton">
        Click here
    </button>
</p>

@code {
    public void OnClickTitle(MouseEventArgs args)
    {
        Console.WriteLine($"Title was clicked! - CtrlKey:{args.CtrlKey}");
    }

    public void OnClickButton(MouseEventArgs args)
    {
        Console.WriteLine($"Button was clicked! - CtrlKey:{args.CtrlKey}");
    }
}
```

![image](https://user-images.githubusercontent.com/95908/84568400-37358c80-adba-11ea-822e-846f0383aa27.png)

I attached this sample program code, so you can download it from below.

- [BlazorApp.zip](https://github.com/jsakamoto/Toolbelt.Blazor.HotKeys/files/4774545/BlazorApp.zip)

**Comment by Yavari** [comment]
I am very sorry that I bothered you with this request. It's clear that I need to read up more about Blazor. I was evaluating it for a project I currently have written in Angular and this was the only thing preventing me from rewriting it Blazor.
Thank you!

**Comment by jsakamoto** [comment]
@Yavari You are welcome!

I could produce a new feature from your request.
This new feature - support for meta key only events - must be helpful for somebody in the future.

Happy coding! 👍
