### ISSUE TITLE
Add support for CMD-key modifier on macOS

### ISSUE THREAD

**Issue by Mindorf** [jsakamoto/Toolbelt.Blazor.HotKeys#5]
Currently the library has CTRL, ALT and SHIFT available in the ModKey enum. Would be a nice feature to add CMD key to use on macOS.

**Comment by jsakamoto** [comment]
@Mindorf 
Sorry too late!

I published a new version of "Blazor WebAssembly HotKeys", v.8.2.0.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys/8.2.0

It supports the "Meta" key modifier in `ModKeys` enum values.

Please try it out!

P.S.
Please remember that the "metaKey" modifier is not compatible between OS and browsers.
See also: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

**Comment by Mindorf** [comment]
@jsakamoto excellent! It works like a charm. Thank you very much.
