### ISSUE TITLE
AllowIn non-text inputs

### ISSUE THREAD

**Issue by andrewlock** [jsakamoto/Toolbelt.Blazor.HotKeys#7]
The `AllowIn` enum allows enabling hotkeys in `Input` and/or `TextArea`  - I would like to allow the hotkey to be enabled when a checkbox/radio button etc has focus, i.e. a non-text `input`.

It would require threading the input type through from the js. 

Is that something you would be happy to add? I am happy to put together a PR if you would like?

**Comment by jsakamoto** [comment]
Yes, it sounds like good improvement for me.

If you send a pull request to me, I'm appreciate for your contribution. 👍

**Comment by jsakamoto** [comment]
@andrewlock 

I published a new version of this package.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys/8.3.0

Thanks!

**Comment by andrewlock** [comment]
Thanks, appreciate it! ♥️
